name: hotel-booking

channels:
  - conda-forge

dependencies:
  - python=3.12.7

  - pip

  - pip:
      - mlflow==2.19.0
      - dagshub
      - matplotlib
      - numpy
      - optuna
      - pandas
      - python-dotenv
      - scikit-learn
      - xgboost
