name: Workflow CI

on:
  push:
    branches:
      - main

jobs:
  mlops:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Install Dependency
        run: |
          pip install mlflow==2.19.0
          pip install dagshub
          pip install matplotlib
          pip install numpy
          pip install optuna
          pip install pandas
          pip install python-dotenv
          pip install scikit-learn
          pip install xgboost

      - name: Run Training
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/artifacts/model

      - name: Build Docker
        run: |
          mlflow models build-docker \
          --model-uri MLProject/artifacts/model \
          --name hotel-booking-model \
          --env-manager=local

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "feryanuar24"
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag \
          hotel-booking-model \
          feryanuar24/hotel-booking-model:latest

      - name: Push Docker Image
        run: |
          docker push \
          feryanuar24/hotel-booking-model:latest

      - name: Docker Hub Link
        run: |
          echo ""
          echo "========================================"
          echo "Docker Image"
          echo ""
          echo "https://hub.docker.com/r/feryanuar24/hotel-booking-model"
          echo "========================================"
